# CMake generated Testfile for 
# Source directory: C:/dev/log4cpp/log4cpp/tests
# Build directory: C:/dev/log4cpp/log4cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testCategory "C:/dev/log4cpp/log4cpp/tests/Debug/testCategory.exe")
  set_tests_properties(testCategory PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testCategory "C:/dev/log4cpp/log4cpp/tests/Release/testCategory.exe")
  set_tests_properties(testCategory PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testCategory "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testCategory.exe")
  set_tests_properties(testCategory PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testCategory "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testCategory.exe")
  set_tests_properties(testCategory PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testCategory NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testFixedContextCategory "C:/dev/log4cpp/log4cpp/tests/Debug/testFixedContextCategory.exe")
  set_tests_properties(testFixedContextCategory PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testFixedContextCategory "C:/dev/log4cpp/log4cpp/tests/Release/testFixedContextCategory.exe")
  set_tests_properties(testFixedContextCategory PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testFixedContextCategory "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testFixedContextCategory.exe")
  set_tests_properties(testFixedContextCategory PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testFixedContextCategory "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testFixedContextCategory.exe")
  set_tests_properties(testFixedContextCategory PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testFixedContextCategory NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testNDC "C:/dev/log4cpp/log4cpp/tests/Debug/testNDC.exe")
  set_tests_properties(testNDC PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testNDC "C:/dev/log4cpp/log4cpp/tests/Release/testNDC.exe")
  set_tests_properties(testNDC PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testNDC "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testNDC.exe")
  set_tests_properties(testNDC PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testNDC "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testNDC.exe")
  set_tests_properties(testNDC PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testNDC NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testPattern "C:/dev/log4cpp/log4cpp/tests/Debug/testPattern.exe")
  set_tests_properties(testPattern PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testPattern "C:/dev/log4cpp/log4cpp/tests/Release/testPattern.exe")
  set_tests_properties(testPattern PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testPattern "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testPattern.exe")
  set_tests_properties(testPattern PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testPattern "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testPattern.exe")
  set_tests_properties(testPattern PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testPattern NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testErrorCollision "C:/dev/log4cpp/log4cpp/tests/Debug/testErrorCollision.exe")
  set_tests_properties(testErrorCollision PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testErrorCollision "C:/dev/log4cpp/log4cpp/tests/Release/testErrorCollision.exe")
  set_tests_properties(testErrorCollision PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testErrorCollision "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testErrorCollision.exe")
  set_tests_properties(testErrorCollision PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testErrorCollision "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testErrorCollision.exe")
  set_tests_properties(testErrorCollision PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testErrorCollision NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testPriority "C:/dev/log4cpp/log4cpp/tests/Debug/testPriority.exe")
  set_tests_properties(testPriority PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testPriority "C:/dev/log4cpp/log4cpp/tests/Release/testPriority.exe")
  set_tests_properties(testPriority PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testPriority "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testPriority.exe")
  set_tests_properties(testPriority PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testPriority "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testPriority.exe")
  set_tests_properties(testPriority PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testPriority NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testFilter "C:/dev/log4cpp/log4cpp/tests/Debug/testFilter.exe")
  set_tests_properties(testFilter PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testFilter "C:/dev/log4cpp/log4cpp/tests/Release/testFilter.exe")
  set_tests_properties(testFilter PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testFilter "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testFilter.exe")
  set_tests_properties(testFilter PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testFilter "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testFilter.exe")
  set_tests_properties(testFilter PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testFilter NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testProperties "C:/dev/log4cpp/log4cpp/tests/Debug/testProperties.exe")
  set_tests_properties(testProperties PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testProperties "C:/dev/log4cpp/log4cpp/tests/Release/testProperties.exe")
  set_tests_properties(testProperties PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testProperties "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testProperties.exe")
  set_tests_properties(testProperties PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testProperties "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testProperties.exe")
  set_tests_properties(testProperties PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testProperties NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testConfig "C:/dev/log4cpp/log4cpp/tests/Debug/testConfig.exe")
  set_tests_properties(testConfig PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testConfig "C:/dev/log4cpp/log4cpp/tests/Release/testConfig.exe")
  set_tests_properties(testConfig PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testConfig "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testConfig.exe")
  set_tests_properties(testConfig PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testConfig "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testConfig.exe")
  set_tests_properties(testConfig PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testConfig NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testPropertyConfig "C:/dev/log4cpp/log4cpp/tests/Debug/testPropertyConfig.exe")
  set_tests_properties(testPropertyConfig PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testPropertyConfig "C:/dev/log4cpp/log4cpp/tests/Release/testPropertyConfig.exe")
  set_tests_properties(testPropertyConfig PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testPropertyConfig "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testPropertyConfig.exe")
  set_tests_properties(testPropertyConfig PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testPropertyConfig "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testPropertyConfig.exe")
  set_tests_properties(testPropertyConfig PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testPropertyConfig NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testRollingFileAppender "C:/dev/log4cpp/log4cpp/tests/Debug/testRollingFileAppender.exe")
  set_tests_properties(testRollingFileAppender PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testRollingFileAppender "C:/dev/log4cpp/log4cpp/tests/Release/testRollingFileAppender.exe")
  set_tests_properties(testRollingFileAppender PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testRollingFileAppender "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testRollingFileAppender.exe")
  set_tests_properties(testRollingFileAppender PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testRollingFileAppender "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testRollingFileAppender.exe")
  set_tests_properties(testRollingFileAppender PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testRollingFileAppender NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testDailyRollingFileAppender "C:/dev/log4cpp/log4cpp/tests/Debug/testDailyRollingFileAppender.exe")
  set_tests_properties(testDailyRollingFileAppender PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testDailyRollingFileAppender "C:/dev/log4cpp/log4cpp/tests/Release/testDailyRollingFileAppender.exe")
  set_tests_properties(testDailyRollingFileAppender PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testDailyRollingFileAppender "C:/dev/log4cpp/log4cpp/tests/MinSizeRel/testDailyRollingFileAppender.exe")
  set_tests_properties(testDailyRollingFileAppender PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testDailyRollingFileAppender "C:/dev/log4cpp/log4cpp/tests/RelWithDebInfo/testDailyRollingFileAppender.exe")
  set_tests_properties(testDailyRollingFileAppender PROPERTIES  _BACKTRACE_TRIPLES "C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;41;add_test;C:/dev/log4cpp/log4cpp/tests/CMakeLists.txt;0;")
else()
  add_test(testDailyRollingFileAppender NOT_AVAILABLE)
endif()
